"""Local repo discovery: the current repo as a source-agent pattern reference.

Read-only, network-free, credential-free. It inspects file *names* and counts
(never file contents) to map the modules a future Jira/GitHub source agent
should mirror — connectors, agent pipelines, safety guards, graph/finding flow.
Output is a deterministic structure plus an audit markdown, written locally.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Any

# Directories surveyed for the structure map: (relative path, file glob).
SURVEY_AREAS: tuple[tuple[str, str], ...] = (
    ("app/services", "*.py"),
    ("app/api", "*.py"),
    ("app/db", "*.py"),
    ("app/connectors", "*.py"),
    ("app/agents", "*.py"),
    ("app/integrations", "*.py"),
    ("app/events", "*.py"),
    ("app/core", "*.py"),
    ("scripts", "*.py"),
    ("tests", "test_*.py"),
    ("docs", "*.md"),
    ("migrations/versions", "*.py"),
)

# Service-module name markers → functional category.
CATEGORY_MARKERS: dict[str, tuple[str, ...]] = {
    "connectors_and_discovery": ("connector", "discovery", "source_", "external_"),
    "agents_and_pipeline": ("agent", "pipeline", "extraction", "runner", "chunk", "ingestion"),
    "guards_and_safety": (
        "guard",
        "sanitiz",
        "redact",
        "secret",
        "visibility",
        "approval",
        "production_operation",
    ),
    "graph_and_findings": ("graph", "finding", "second_opinion", "entity", "evidence"),
    "status_and_state": ("status", "state", "snapshot", "operating_rhythm", "attention"),
    "digest_and_delivery": ("digest", "delivery", "telegram", "notification", "share"),
}

# The canonical modules a new source agent mirrors (the established contract).
SOURCE_AGENT_PATTERN_REFERENCE: tuple[str, ...] = (
    "app/services/discovery_core.py",
    "app/services/jira_discovery.py",
    "app/services/github_discovery.py",
    "app/services/write_action_guard.py",
    "app/services/provider_execution_guard.py",
    "app/services/connector_clients.py",
    "app/services/source_ingestion.py",
    "app/services/second_opinion.py",
)


def discover_local_repo(root: Path) -> dict[str, Any]:
    """Build a deterministic map of the repo's source-agent-relevant modules."""

    root = Path(root)
    structure = {area: _count_files(root / area, glob) for area, glob in SURVEY_AREAS}
    service_names = _module_names(root / "app/services", "*.py")
    categories = {
        category: sorted(
            name for name in service_names if any(marker in name for marker in markers)
        )
        for category, markers in CATEGORY_MARKERS.items()
    }
    reference_present = {path: (root / path).is_file() for path in SOURCE_AGENT_PATTERN_REFERENCE}

    return {
        "report_kind": "local_repo_discovery_summary",
        "structure": structure,
        "service_module_count": len(service_names),
        "categories": categories,
        "source_agent_pattern_reference": reference_present,
        "source_agent_contract": [
            "connector: GET-only client + injectable transport (jira_discovery/github_discovery)",
            "credentials: presence-only preflight, exact missing var names (discovery_core)",
            "safe output: full data local under .local/, sanitized counts to stdout",
            "writes: only via write_action_guard (feature flag + approved proposal + ack)",
            "normalize: source events -> graph (source_ingestion)",
            "reason: second-opinion findings over declared-vs-observed state",
        ],
    }


def _count_files(directory: Path, glob: str) -> int:
    if not directory.is_dir():
        return 0
    return sum(
        1 for path in directory.rglob(glob) if "__pycache__" not in path.parts and path.is_file()
    )


def _module_names(directory: Path, glob: str) -> list[str]:
    if not directory.is_dir():
        return []
    return sorted(
        path.stem for path in directory.glob(glob) if path.is_file() and path.stem != "__init__"
    )


def render_local_repo_audit(summary: Mapping[str, Any]) -> str:
    structure = summary.get("structure", {})
    categories = summary.get("categories", {})
    reference = summary.get("source_agent_pattern_reference", {})

    lines = [
        "# Local Repo Audit (source-agent pattern reference)",
        "",
        "Generated by `scripts/run_local_repo_discovery.py`. Read-only, no network,",
        "no credentials. The current repo is the reference architecture each new",
        "per-source agent (Jira, GitHub, Gmail, transcripts, documents) mirrors.",
        "",
        "## Structure",
        "",
        *(f"- {area}: {count}" for area, count in structure.items()),
        "",
        f"Total app/services modules: {summary.get('service_module_count', 0)}",
        "",
        "## Service modules by category",
        "",
    ]
    for category, names in categories.items():
        lines.append(f"### {category} ({len(names)})")
        lines.append("")
        lines.extend(f"- {name}" for name in names)
        lines.append("")

    lines += [
        "## Source-agent pattern reference",
        "",
        *(f"- [{'x' if present else ' '}] {path}" for path, present in reference.items()),
        "",
        "## Source-agent contract (each source mirrors this)",
        "",
        *(f"- {item}" for item in summary.get("source_agent_contract", [])),
        "",
    ]
    return "\n".join(lines)
