"""Strict contracts for FounderOS Repository Intelligence."""

from app.services.repository_intelligence.contracts import (
    HumanResolutionV1,
    RepositoryIntelligenceV1,
    validate_repository_intelligence_json,
)
from app.services.repository_intelligence.checkout import (
    MaterializedRepositoryCheckout,
    RepositoryCheckoutPolicy,
    RepositoryCheckoutRequest,
    materialize_repository_checkout,
)
from app.services.repository_intelligence.collectors import (
    RepositoryStaticCollectionV1,
    RepositoryStaticCollectorPolicy,
    RepositoryStaticFactV1,
    collect_repository_static_facts,
    validate_repository_static_collection_json,
)
from app.services.repository_intelligence.cross_source import (
    RepositoryCrossSourceClaimSetV1,
    RepositoryCrossSourceClaimV1,
    build_repository_cross_source_comparisons,
)
from app.services.repository_intelligence.l0 import (
    build_workspace_repository_intelligence_l0,
)
from app.services.repository_intelligence.l2_isolation import (
    RepositoryL2Check,
    RepositoryL2CheckReceiptV1,
    RepositoryL2IsolationPolicy,
    RepositoryL2IsolationReceiptV1,
    RepositoryL2IsolationRequest,
    RepositoryL2IsolationStatusReceiptV1,
    RepositoryL2Profile,
    get_hostile_synthetic_l2_isolation_status,
    verify_hostile_synthetic_l2_isolation,
)
from app.services.repository_intelligence.portfolio_dry_run import (
    RepositoryPortfolioDryRunEntryV1,
    RepositoryPortfolioDryRunManifestV1,
    RepositoryPortfolioDryRunReceiptV1,
    RepositoryPortfolioSourceMode,
    prepare_repository_portfolio_dry_run,
    validate_repository_portfolio_dry_run_json,
)
from app.services.repository_intelligence.persistence import (
    RepositoryAnalysisRequestV1,
    RepositoryArtifactDeletionReceipt,
    RepositoryArtifactManifestItemV1,
    RepositoryCoverageV1,
    RepositoryIntelligenceDeletionResult,
    claim_repository_analysis_job,
    confirm_repository_artifacts_deleted,
    delete_repository_intelligence_records,
    enqueue_repository_analysis_job,
    fail_repository_analysis_job,
    list_expired_repository_artifacts,
    persist_repository_intelligence_result,
    request_repository_analysis_cancellation,
)
from app.services.repository_intelligence.relationships import (
    RepositoryPortfolioEntryV1,
    RepositoryPortfolioV1,
    RepositoryRelationshipAnalysisV1,
    RepositoryRelationshipPolicy,
    RepositoryRelationshipSignalV1,
    build_repository_relationship_analysis,
    is_relationship_fact_type,
    relationship_signals_from_static_collection,
    validate_repository_relationship_analysis_json,
)

__all__ = [
    "HumanResolutionV1",
    "MaterializedRepositoryCheckout",
    "RepositoryCheckoutPolicy",
    "RepositoryCheckoutRequest",
    "RepositoryIntelligenceV1",
    "RepositoryL2Check",
    "RepositoryL2CheckReceiptV1",
    "RepositoryL2IsolationPolicy",
    "RepositoryL2IsolationReceiptV1",
    "RepositoryL2IsolationRequest",
    "RepositoryL2IsolationStatusReceiptV1",
    "RepositoryL2Profile",
    "RepositoryAnalysisRequestV1",
    "RepositoryArtifactDeletionReceipt",
    "RepositoryArtifactManifestItemV1",
    "RepositoryCoverageV1",
    "RepositoryCrossSourceClaimSetV1",
    "RepositoryCrossSourceClaimV1",
    "RepositoryIntelligenceDeletionResult",
    "RepositoryPortfolioDryRunEntryV1",
    "RepositoryPortfolioDryRunManifestV1",
    "RepositoryPortfolioDryRunReceiptV1",
    "RepositoryPortfolioSourceMode",
    "RepositoryPortfolioEntryV1",
    "RepositoryPortfolioV1",
    "RepositoryRelationshipAnalysisV1",
    "RepositoryRelationshipPolicy",
    "RepositoryRelationshipSignalV1",
    "RepositoryStaticCollectionV1",
    "RepositoryStaticCollectorPolicy",
    "RepositoryStaticFactV1",
    "build_workspace_repository_intelligence_l0",
    "build_repository_cross_source_comparisons",
    "build_repository_relationship_analysis",
    "collect_repository_static_facts",
    "claim_repository_analysis_job",
    "confirm_repository_artifacts_deleted",
    "delete_repository_intelligence_records",
    "enqueue_repository_analysis_job",
    "fail_repository_analysis_job",
    "is_relationship_fact_type",
    "list_expired_repository_artifacts",
    "materialize_repository_checkout",
    "persist_repository_intelligence_result",
    "prepare_repository_portfolio_dry_run",
    "relationship_signals_from_static_collection",
    "request_repository_analysis_cancellation",
    "validate_repository_relationship_analysis_json",
    "validate_repository_static_collection_json",
    "validate_repository_intelligence_json",
    "validate_repository_portfolio_dry_run_json",
    "get_hostile_synthetic_l2_isolation_status",
    "verify_hostile_synthetic_l2_isolation",
]
