"""Stage 20: the Obsidian generator is Russian-first.

These tests pin the founder-facing localization of the vault generator:
- node/task note H1 uses the Russian title (title_ru/name_ru) when present;
- the technical key (Jira key) stays visible in the body and frontmatter;
- section headings, the FounderOS notice, and common labels are Russian;
- no English primary headings (e.g. ``## Summary``) remain in any note;
- wikilinks, frontmatter, secret-safety, and path safety are preserved.
"""

from __future__ import annotations

import pytest

from app.db.base import AsyncSessionLocal
from app.services.obsidian_vault import (
    RU_NOTICE,
    _assert_markdown_safe,
    _node_note,
    display_summary_for_node,
    display_title_for_node,
    generate_obsidian_vault_plan,
    status_ru_label,
)

# English primary headings / notices that must never appear in a generated note.
FORBIDDEN_ENGLISH = (
    "## Summary",
    "## Properties",
    "## Backlinks",
    "## Outgoing Links",
    "## Evidence\n",
    "## Related Findings",
    "## Related Actions",
    "## Source Lineage",
    "## Decision History",
    "## Data Quality",
    "## Security Policy",
    "## Connectors\n",
    "## Pipeline States",
    "## Next Steps",
    "## Scope & Limits",
    "## Last Activity",
    "## Sections",
    "## Graph Stats",
    "## Real Execution",
    "Generated by FounderOS",
)


def _make_note(node: dict, *, links_to: dict | None = None):
    """Render a single node note in isolation (no DB)."""
    node_id = str(node["node_id"])
    node_path_map = {node_id: f"Tasks/{node_id}.md"}
    node_lookup = {node_id: node}
    edges: list[dict] = []
    if links_to is not None:
        target_id = str(links_to["node_id"])
        node_path_map[target_id] = "Products/backend.md"
        node_lookup[target_id] = links_to
        edges = [
            {
                "source_node_id": node_id,
                "target_node_id": target_id,
                "edge_type": "depends_on",
            }
        ]
    return _node_note(
        node,
        edges=edges,
        node_path_map=node_path_map,
        node_lookup=node_lookup,
    )


def test_task_note_h1_is_russian_and_keeps_jira_key() -> None:
    node = {
        "node_id": "task:jira:core-1",
        "node_type": "issue",
        "title": "CORE-1",
        "summary": "CORE-1",
        "properties": {
            "jira_key": "CORE-1",
            "title_ru": "Согласовать UX передачи потокового чата",
            "status": "Backlog",
        },
    }
    note = _make_note(node)
    md = note.markdown

    # H1 is the Russian issue title, not the raw key.
    assert "# Согласовать UX передачи потокового чата" in md
    assert "\n# CORE-1\n" not in md
    # The Jira key is still clearly present (body + frontmatter alias).
    assert "Ключ Jira: `CORE-1`" in md
    assert "CORE-1" in note.frontmatter["aliases"]
    assert note.title == "Согласовать UX передачи потокового чата"


def test_repo_component_note_uses_name_ru() -> None:
    node = {
        "node_id": "repository:qaztwin-ssap-frontend",
        "node_type": "repo",
        "title": "qaztwin-ssap-frontend",
        "properties": {
            "name_ru": "веб-клиент (продуктовый интерфейс)",
            "entity_role": "component",
        },
    }
    note = _make_note(node)
    assert "# веб-клиент (продуктовый интерфейс)" in note.markdown
    # Technical repo name remains discoverable as an alias.
    assert "qaztwin-ssap-frontend" in note.frontmatter["aliases"]


def test_common_headings_and_notice_are_russian() -> None:
    node = {
        "node_id": "project:core",
        "node_type": "project",
        "title": "CORE",
        "properties": {"name_ru": "Ядро продукта", "status": "active"},
    }
    md = _make_note(node).markdown
    for heading in (
        "## Кратко",
        "## Свойства",
        "## Обратные ссылки",
        "## Исходящие связи",
        "## Подтверждения",
        "## Связанные выводы FounderOS",
        "## Следующие действия",
        "## Происхождение данных",
        "## История решений",
        "## Качество данных",
    ):
        assert heading in md, heading
    assert RU_NOTICE.split("\n")[0] in md
    for forbidden in FORBIDDEN_ENGLISH:
        assert forbidden not in md, forbidden


def test_summary_and_status_fall_back_to_russian() -> None:
    # Only a raw key as title/summary -> summary uses Russian title, never key.
    node = {
        "node_id": "task:jira:core-2",
        "node_type": "issue",
        "title": "CORE-2",
        "summary": "CORE-2",
        "properties": {
            "jira_key": "CORE-2",
            "title_ru": "Backend реализовать SSE-транспорт",
            "status": "In Progress",
        },
    }
    assert display_summary_for_node(node) == "Backend реализовать SSE-транспорт"
    # Status keeps the raw value and adds a Russian explanation.
    assert status_ru_label(node) == "`In Progress` (в работе)"


def test_human_readable_title_used_and_key_fallback() -> None:
    readable = {
        "node_id": "project:alpha",
        "node_type": "project",
        "title": "Project Alpha",
        "properties": {},
    }
    assert display_title_for_node(readable) == "Project Alpha"
    # No Russian and title is a technical key -> fall back to the key.
    keyed = {
        "node_id": "task:jira:widget-9",
        "node_type": "issue",
        "title": "WIDGET-9",
        "properties": {"jira_key": "WIDGET-9"},
    }
    assert display_title_for_node(keyed) == "WIDGET-9"


def test_wikilink_labels_use_russian_display_title() -> None:
    source = {
        "node_id": "task:jira:core-3",
        "node_type": "issue",
        "title": "CORE-3",
        "properties": {"title_ru": "Frontend подключить отображение SSE-потока"},
    }
    target = {
        "node_id": "repository:backend",
        "node_type": "repo",
        "title": "qaztwin-ssap-backend",
        "properties": {"name_ru": "серверная часть"},
    }
    note = _make_note(source, links_to=target)
    # Wikilink target is the path; label is the Russian display title.
    assert "[[Products/backend|серверная часть]]" in note.markdown


async def test_generated_plan_has_no_english_headings_and_is_safe() -> None:
    async with AsyncSessionLocal() as session:
        plan = await generate_obsidian_vault_plan(session)
    assert plan.notes
    for note in plan.notes:
        md = note.markdown
        # Frontmatter is well-formed and content_hash present.
        assert md.startswith("---\n")
        assert "\ncontent_hash:" in md
        assert "\n---\n" in md[4:]
        # No English primary headings or English notice anywhere.
        for forbidden in FORBIDDEN_ENGLISH:
            assert forbidden not in md, f"{forbidden} in {note.path}"
        # Secret-safety guard still holds for every note.
        _assert_markdown_safe(md)


@pytest.mark.parametrize(
    "value",
    ["CORE-1", "ABC-123", "PROJ-9999"],
)
def test_jira_key_regex_detects_technical_keys(value: str) -> None:
    node = {"node_id": "n", "node_type": "issue", "title": value, "properties": {}}
    # A bare Jira key is treated as non-human-readable, so it is only the
    # fallback title (Russian fields win when present).
    assert display_title_for_node(node) == value
    node_ru = dict(node, properties={"title_ru": "Человеческий заголовок"})
    assert display_title_for_node(node_ru) == "Человеческий заголовок"
