"""add extracted tasks

Revision ID: db24cd5c2bd4
Revises: d7ab50f1b82e
Create Date: 2026-04-25 23:59:56.124357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db24cd5c2bd4'
down_revision: Union[str, Sequence[str], None] = 'd7ab50f1b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_event_id', sa.String(length=120), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_tasks_source_event_id'), 'extracted_tasks', ['source_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_tasks_source_event_id'), table_name='extracted_tasks')
    op.drop_table('extracted_tasks')
    # ### end Alembic commands ###
