#!/usr/bin/env python3
"""Prepare local GitHub repository discovery inputs from .local/repos.json.

This helper is intentionally offline: it reads an existing local repository list,
normalizes the small subset of fields FounderOS needs, writes the canonical local
snapshot layout used by repo audit/inventory code, and optionally writes a safe
local env snippet with repository allowlists. It never calls GitHub and never
handles provider tokens.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_REPO_FULL_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
_DEFAULT_SNAPSHOT_PREFIX = "local-repos"
_SENSITIVE_KEY_MARKERS = ("token", "secret", "password", "credential", "authorization")


class SnapshotPreparationError(ValueError):
    """Raised when the local repository surface cannot be prepared safely."""


def main() -> int:
    args = _parse_args()
    source = Path(args.source)
    workspace = Path(args.workspace)
    repos = load_and_normalize_repositories(source)
    snapshot_id = args.snapshot_id or _default_snapshot_id()
    raw_path = write_discovery_snapshot(
        workspace=workspace,
        snapshot_id=snapshot_id,
        repositories=repos,
    )
    env_path: Path | None = None
    if not args.no_env:
        env_path = write_repository_env_snippet(
            workspace=workspace,
            repositories=repos,
            output_path=Path(args.env_output) if args.env_output else None,
        )

    print(f"Prepared {len(repos)} GitHub repositories")
    print(f"Discovery snapshot: {raw_path}")
    if env_path is not None:
        print(f"Repository env snippet: {env_path}")
    print("No network calls, provider writes, or secrets were used.")
    return 0


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare local FounderOS GitHub repository discovery inputs."
    )
    parser.add_argument(
        "--source",
        default=".local/repos.json",
        help="Path to the existing local repository list (default: .local/repos.json).",
    )
    parser.add_argument(
        "--workspace",
        default=".local",
        help="FounderOS local workspace path (default: .local).",
    )
    parser.add_argument(
        "--snapshot-id",
        default=None,
        help="Snapshot id under discovery/github/<id>/raw/repos.json.",
    )
    parser.add_argument(
        "--env-output",
        default=None,
        help="Optional output path for safe repository env snippet.",
    )
    parser.add_argument(
        "--no-env",
        action="store_true",
        help="Do not write the local repository env snippet.",
    )
    return parser.parse_args()


def load_and_normalize_repositories(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SnapshotPreparationError(f"repository list not found: {path}")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SnapshotPreparationError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(raw, list):
        raise SnapshotPreparationError("repository list must be a JSON array")

    normalized: dict[str, dict[str, Any]] = {}
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise SnapshotPreparationError(f"repository item #{index + 1} must be an object")
        repo = _normalize_repository(item, index=index)
        normalized[repo["full_name"]] = repo
    return [normalized[key] for key in sorted(normalized)]


def write_discovery_snapshot(
    *,
    workspace: Path,
    snapshot_id: str,
    repositories: list[dict[str, Any]],
) -> Path:
    if not snapshot_id or any(part in snapshot_id for part in ("/", "\\", "..")):
        raise SnapshotPreparationError("snapshot id must be a simple path segment")
    raw_dir = workspace / "discovery" / "github" / snapshot_id / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    raw_path = raw_dir / "repos.json"
    raw_path.write_text(
        json.dumps(repositories, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return raw_path


def write_repository_env_snippet(
    *,
    workspace: Path,
    repositories: list[dict[str, Any]],
    output_path: Path | None = None,
) -> Path:
    output = output_path or (workspace / "github-repositories.env")
    output.parent.mkdir(parents=True, exist_ok=True)
    full_names = ",".join(repo["full_name"] for repo in repositories)
    output.write_text(
        "# Generated by scripts/prepare_github_local_snapshot.py\n"
        "# Safe local repository allowlists only. No tokens or secrets are stored here.\n"
        f"FOUNDEROS_GITHUB_REPOS={full_names}\n"
        f"FOS_GITHUB_SYNC_ALLOWED_REPOS={full_names}\n"
        "# Keep provider writes disabled by default; set a minimal write allowlist manually only for an approved smoke repo.\n"
        "# FOS_GITHUB_WRITE_ALLOWED_REPOS=<owner/repo>\n",
        encoding="utf-8",
    )
    return output


def _normalize_repository(item: dict[str, Any], *, index: int) -> dict[str, Any]:
    _reject_sensitive_keys(item, path=f"repo[{index}]")
    full_name = _safe_full_name(item.get("full_name"))
    if full_name is None:
        owner = _owner_login(item.get("owner"))
        name = _safe_repo_part(item.get("name"))
        if owner and name:
            full_name = f"{owner}/{name}"
    if full_name is None:
        raise SnapshotPreparationError(
            f"repository item #{index + 1} has no valid full_name"
        )
    owner_login, repo_name = full_name.split("/", 1)
    name = _safe_repo_part(item.get("name")) or repo_name
    private = bool(item.get("private"))
    normalized = {
        "full_name": full_name,
        "name": name,
        "owner": {"login": owner_login},
        "private": private,
        "visibility": "private" if private else "public",
        "archived": bool(item.get("archived")),
        "fork": bool(item.get("fork")),
        "default_branch": _safe_text(item.get("default_branch")),
        "language": _safe_text(item.get("language")),
        "description": _safe_text(item.get("description"), limit=500),
        "html_url": _safe_url(item.get("html_url")) or f"https://github.com/{full_name}",
        "source_url": _safe_url(item.get("source_url"))
        or _safe_url(item.get("html_url"))
        or f"https://github.com/{full_name}",
        "pushed_at": _safe_text(item.get("pushed_at")),
        "updated_at": _safe_text(item.get("updated_at")),
    }
    return {key: value for key, value in normalized.items() if value is not None}


def _reject_sensitive_keys(value: Any, *, path: str) -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            if any(marker in str(key).casefold() for marker in _SENSITIVE_KEY_MARKERS):
                raise SnapshotPreparationError(
                    f"refusing to copy sensitive-looking key at {path}.{key}"
                )
            _reject_sensitive_keys(child, path=f"{path}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            _reject_sensitive_keys(child, path=f"{path}[{index}]")


def _default_snapshot_id() -> str:
    return f"{_DEFAULT_SNAPSHOT_PREFIX}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"


def _safe_full_name(value: Any) -> str | None:
    text = _safe_text(value, limit=255)
    if not text or not _REPO_FULL_NAME_RE.fullmatch(text):
        return None
    return text


def _owner_login(value: Any) -> str | None:
    if isinstance(value, dict):
        return _safe_repo_part(value.get("login"))
    return _safe_repo_part(value)


def _safe_repo_part(value: Any) -> str | None:
    text = _safe_text(value, limit=120)
    if not text or not re.fullmatch(r"[A-Za-z0-9_.-]+", text):
        return None
    return text


def _safe_url(value: Any) -> str | None:
    text = _safe_text(value, limit=1000)
    if text and text.startswith(("https://", "http://")):
        return text
    return None


def _safe_text(value: Any, *, limit: int = 255) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    return text[:limit]


if __name__ == "__main__":
    raise SystemExit(main())
